const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#2d6a4f",
    background: "#f8f9fa",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#2d6a4f",
    primaryForeground: "#ffffff",
    secondary: "#e8f5e9",
    secondaryForeground: "#1b5e20",
    muted: "#f1f3f4",
    mutedForeground: "#6b7280",
    accent: "#c8a84b",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    gold: "#c8a84b",
    goldLight: "#f0d080",
  },
  dark: {
    text: "#f5f5f5",
    tint: "#c8a84b",
    background: "#0f0f0f",
    foreground: "#f5f5f5",
    card: "#1a1a1a",
    cardForeground: "#f5f5f5",
    primary: "#c8a84b",
    primaryForeground: "#0f0f0f",
    secondary: "#2a2a2a",
    secondaryForeground: "#e5e5e5",
    muted: "#1f1f1f",
    mutedForeground: "#9ca3af",
    accent: "#c8a84b",
    accentForeground: "#0f0f0f",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    gold: "#c8a84b",
    goldLight: "#f0d080",
  },
  radius: 12,
};

export default colors;
